[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name        = "rbc-tracking-model"
version     = "0.1.0"
description = "Red-blood-cell tracking toolkit"
readme      = "README.md"
authors     = [{name = "Your Name"}]
dependencies = [
  "numpy",
  "pandas",
  "igraph",
  "pyvista",
  "tqdm"
]

[tool.setuptools]

packages = ["tracking_model"]           

[tool.setuptools.package-data]
# "tracking_model" = ["data/**/*.csv", "data/**/*.vtk"]
